### ISSUE TITLE
vendor not publish

### ISSUE THREAD

**Issue by shrenik9** [vmitchell85/spark-kiosk-notify#1]
when I am going to run this command  'php artisan vendor:publish --provider="vmitchell85\SparkKioskNotify\src\SparkKioskNotifyServiceProvider"' that show me "Nothing to publish for tag []."

**Comment by vmitchell85** [comment]
@shrenik9 I'll try to check this out and get back to you...

**Comment by vmitchell85** [comment]
@shrenik9 I've fixed this issue. Please install version 1.0.2 and follow the updated instructions in the readme. Thanks!
