### ISSUE TITLE
Cannot see any users in dropdown

### ISSUE THREAD

**Issue by justashton** [vmitchell85/spark-kiosk-notify#7]
Title say's it all.

**Comment by vmitchell85** [comment]
What version of Spark are you using? This hasn't yet been updated to work with Spark 3.0/VueJS 2.0

**Comment by justashton** [comment]
Ah yeah I'm using the newest version. That would explain it.

**Comment by vmitchell85** [comment]
There is a PR for Vue 2.0 updates... let me test it out and I'll see if I can get it released this morning...

**Comment by vmitchell85** [comment]
I've merged #6 which updates the package to Vue 2 and created a new 2.0 release.

**Comment by justashton** [comment]
Thank you heaps this saves me a lot of work. Cheers
